### ISSUE TITLE
Composer Issue

### ISSUE THREAD

**Issue by wke102** [pixwell-dev/laravel-adyen#3]
Problem 1
    - Installation request for pixwell-dev/laravel-adyen ^0.0.1 -> satisfiable by pixwell-dev/laravel-adyen[0.0.1].
    - pixwell-dev/laravel-adyen 0.0.1 requires illuminate/support ~5.4.0 -> satisfiable by illuminate/support[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9] but these conflict with your requirements or minimum-stability.

How can i fix this? Already included everything in composer.

"require": {
        "php": ">=7.0.0",
        "adyen/php-api-library": "^1.4",
        "cviebrock/eloquent-sluggable": "^4.3",
        "fideloper/proxy": "~3.3",
        "google/apiclient": "^2.0",
        "illuminate/support": "^5.5",
        "laravel/framework": "5.5.*",
        "laravel/passport": "^4.0",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "nothingworks/blade-svg": "^0.2.2",
        "predis/predis": "^1.1",
        "spatie/laravel-medialibrary": "^6.0.0",
        "tightenco/ziggy": "^0.5.0",
        "torann/currency": "^1.0"
    },

**Comment by jozefbalun** [comment]
resolved in 0.0.2 release
